### ISSUE TITLE
Unable to disable patheon based functionality

### ISSUE THREAD

**Issue by claytoncollie** [cagov/ca-design-system-gutenberg-blocks#80]
Hello. I am currently unable to disable the Pantheon functionality even when not hosted on pantheon. The functionality is effecting the frontend so that is why I am opening this issue and submitting a pull request.

**Comment by claytoncollie** [comment]
Resolved with #79

**Comment by zakiya** [comment]
Sorry for the back and forth. It's been a minute since we looked at the plugin. 

If the goal is to disable the entire conditional, I'd prefer we just delete it. The files in question are actually not in use on any of our production sites and aren't actually Pantheon-specific. They were a temporary work around while we were supporting the plugin on two very different environments.

If it works for your use case, I'll put up a PR tomorrow that removes all of the code in blue. 

![CleanShot 2024-01-25 at 15 52 34@2x](https://github.com/cagov/ca-design-system-gutenberg-blocks/assets/915352/c468b532-cf87-4b22-b77d-21a777c9793a)


cc @chachasikes

**Comment by claytoncollie** [comment]
@zakiya Sounds good to me! Delete away.
